changing init logics, and output

diff --git a/package/kernel-osmc/initramfs-src/init b/package/kernel-osmc/initramfs-src/init
--- a/package/kernel-osmc/initramfs-src/init
+++ b/package/kernel-osmc/initramfs-src/init
@@ -87,23 +87,32 @@ for option in $(/bin/busybox cat /proc/cmdline); do
 		ROOT_STR=$OPTION_ROOT
 		PARTUUID=$(echo "$OPTION_ROOT" | /bin/busybox grep "^PARTUUID=" | /bin/busybox sed 's/^PARTUUID=//g')
 		UUID=$(echo "$OPTION_ROOT" | /bin/busybox grep "^UUID=" | /bin/busybox sed 's/^UUID=//g')
-		if ! [ -z "$UUID$PARTUUID" ]; then
+		DEVSD=$(echo "$OPTION_ROOT" | /bin/busybox grep "^/dev/sd")
+		if ! [ -z "$UUID$PARTUUID$DEVSD" ]; then
 			# it takes a while for USB partitions to show up
-			count=12
+			count=20
 			OPTION_ROOT=
+			echo $(/bin/busybox blkid)
+			echo "Waiting for usb to come up...\n"
 			while [ $count -ge 0 -a -z "$OPTION_ROOT" ]; do
-				echo $count seconds
-				echo $(/bin/busybox blkid)
-				if [ -n "$PARTUUID" ]; then OPTION_ROOT=$(/bin/busybox findfs "PARTUUID=${PARTUUID}"); fi
-				if [ -n "$UUID" ]; then OPTION_ROOT=$(/bin/busybox findfs "UUID=${UUID}"); fi
-				if ! [ -z "$OPTION_ROOT" ]; then break; fi
+				if [ -n "$PARTUUID" ]; then OPTION_ROOT=$(/bin/busybox findfs "PARTUUID=${PARTUUID}");
+				elif [ -n "$UUID" ]; then OPTION_ROOT=$(/bin/busybox findfs "UUID=${UUID}");
+				elif [ -b "$DEVSD" ]; then OPTION_ROOT=$DEVSD;
+				fi
+
+				if ! [ -z "$OPTION_ROOT" ]; then
+					echo "Found device on ${OPTION_ROOT}"
+					break;
+				fi
+
 				count=$((count - 1))
+				echo "\e[1A\e[K${count} seconds"
 				/bin/busybox sleep 1
 			done
 		fi
 		# fallbacks if dev or UUIDs not found
 		if [ -z "$OPTION_ROOT" -o ! -b "$OPTION_ROOT" ]; then
-			echo "          Can\'t find filesystem root for $ROOT_STR"
+			echo "Can't find filesystem root for $ROOT_STR"
 			# booting from SD card with a root partition
 			if [ -b "/dev/mmcblk0p2" ]; then OPTION_ROOT="/dev/mmcblk0p2"
 			# booting from SD with only a boot partition or USB but UUID not recognised
@@ -113,8 +122,7 @@ for option in $(/bin/busybox cat /proc/cmdline); do
 			elif [ -b "/dev/sda1" ]; then OPTION_ROOT="/dev/sda1"
 			else OPTION_ROOT=$ROOT_DEF
 			fi
-			echo "          Guessing root is on $OPTION_ROOT"
-			/bin/busybox sleep 5
+			echo "Guessing root is on $OPTION_ROOT"
 		fi
 		;;
 	  rootfstype=*)
